const KEY='gymtrack_v1';
const SUPABASE_URL = "https://ctfxvknetueqxwbcqhxk.supabase.co";
const SUPABASE_KEY = "sb_publishable_esBGrxErt8VS8KceznnG2w_9InNiZGI";
const defaults={exercises:['Press banca','Sentadilla','Peso muerto','Press inclinado','Remo con barra','Jalón al pecho','Elevaciones laterales','Curl bíceps','Extensión de tríceps','Prensa','Extensión de cuádriceps','Curl femoral','Gemelos'],routines:[{name:'Push',ex:['Press banca','Press inclinado','Elevaciones laterales','Extensión de tríceps']},{name:'Pull',ex:['Remo con barra','Jalón al pecho','Curl bíceps']},{name:'Legs',ex:['Sentadilla','Prensa','Extensión de cuádriceps','Curl femoral','Gemelos']}],workouts:[]};
let db=JSON.parse(localStorage.getItem(KEY)||'null')||defaults; function save(){localStorage.setItem(KEY,JSON.stringify(db));renderAll()} function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function nav(page){$$('.page').forEach(x=>x.classList.toggle('active',x.id===page));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$('#title').textContent={dashboard:'Dashboard',workout:'Entrenamiento',routines:'Rutinas',history:'Historial',exercises:'Ejercicios'}[page]||'Dashboard';window.scrollTo(0,0)}
$$('.nav').forEach(b=>b.onclick=()=>nav(b.dataset.page));$$('.textbtn').forEach(b=>b.onclick=()=>nav(b.dataset.page));$('#quickStart').onclick=()=>{nav('workout');newWorkout()};
function newWorkout(){ $('#workoutName').value='Entrenamiento '+new Date().toLocaleDateString('es-CR',{day:'2-digit',month:'2-digit'}); $('#exerciseLog').innerHTML=''; addExerciseRow(); }
function addExerciseRow(name=''){let box=document.createElement('div');box.className='exercise-card';box.innerHTML=`<div class="panel-head"><select class="exercise-select"><option value="">Seleccionar ejercicio</option>${db.exercises.map(e=>`<option ${e===name?'selected':''}>${esc(e)}</option>`).join('')}</select><button class="danger remove-ex">Eliminar</button></div><div class="sets"></div><button class="secondary add-set">+ Serie</button>`;$('#exerciseLog').appendChild(box);addSet(box);box.querySelector('.add-set').onclick=()=>addSet(box);box.querySelector('.remove-ex').onclick=()=>box.remove()}
function addSet(box){let n=box.querySelectorAll('.set-row').length+1;let row=document.createElement('div');row.className='set-row';row.innerHTML=`<span>${n}</span><input class="input weight" type="number" step="0.5" placeholder="kg"><input class="input reps" type="number" placeholder="reps"><input class="input rpe" type="number" step="0.5" placeholder="RPE"><button class="danger del-set">×</button>`;box.querySelector('.sets').appendChild(row);row.querySelector('.del-set').onclick=()=>{row.remove();box.querySelectorAll('.set-row').forEach((r,i)=>r.firstElementChild.textContent=i+1)}}
$('#addExercise').onclick=()=>addExerciseRow();$('#saveWorkout').onclick=()=>{let ex=[];$$('#exerciseLog .exercise-card').forEach(c=>{let name=c.querySelector('.exercise-select').value;if(!name)return;let sets=[];c.querySelectorAll('.set-row').forEach(r=>{let w=+r.querySelector('.weight').value||0, reps=+r.querySelector('.reps').value||0, rpe=+r.querySelector('.rpe').value||null;if(w&&reps)sets.push({w,reps,rpe})});if(sets.length)ex.push({name,sets})});if(!ex.length)return alert('Agrega al menos un ejercicio con una serie válida.');db.workouts.unshift({id:Date.now(),name:$('#workoutName').value||'Entrenamiento',date:new Date().toISOString(),ex});save();nav('history');};
function renderDashboard(){let ws=db.workouts;$('#statWorkouts').textContent=ws.length;let vol=ws.reduce((a,w)=>a+w.ex.reduce((x,e)=>x+e.sets.reduce((z,s)=>z+s.w*s.reps,0),0),0);$('#statVolume').textContent=Math.round(vol).toLocaleString()+' kg';$('#statExercises').textContent=new Set(ws.flatMap(w=>w.ex.map(e=>e.name))).size;let prs=0;for(let name of db.exercises){let best=0;ws.flatMap(w=>w.ex.filter(e=>e.name===name)).forEach(e=>e.sets.forEach(s=>{let est=s.w*(1+s.reps/30);if(est>best)best=est}));if(best)prs++}$('#statPRs').textContent=prs;$('#recent').innerHTML=ws.slice(0,5).map(w=>`<div class="row"><div><b>${esc(w.name)}</b><div class="statline">${w.ex.length} ejercicios · ${w.ex.reduce((a,e)=>a+e.sets.length,0)} series</div></div><span class="date">${new Date(w.date).toLocaleDateString('es-CR')}</span></div>`).join('')||'<div class="empty">Todavía no hay entrenamientos.</div>';let now=new Date(),days=[];for(let i=6;i>=0;i--){let d=new Date(now);d.setDate(now.getDate()-i);let count=ws.filter(w=>new Date(w.date).toDateString()===d.toDateString()).length;days.push({d,count})}let mx=Math.max(1,...days.map(x=>x.count));$('#week').innerHTML=days.map(x=>`<div class="day"><div class="bar" style="height:${10+x.count/mx*105}px"></div><span>${x.d.toLocaleDateString('es-CR',{weekday:'short'}).slice(0,2)}</span></div>`).join('')}
function renderHistory(){$('#historyList').innerHTML=db.workouts.map(w=>`<div class="row"><div><b>${esc(w.name)}</b><div class="statline">${new Date(w.date).toLocaleString('es-CR')} · ${w.ex.map(e=>esc(e.name)).join(', ')}</div></div><button class="danger" onclick="deleteWorkout(${w.id})">Eliminar</button></div>`).join('')||'<div class="empty">No hay sesiones registradas.</div>'}window.deleteWorkout=id=>{db.workouts=db.workouts.filter(w=>w.id!==id);save()};
function renderRoutines(){$('#routineList').innerHTML=db.routines.map((r,i)=>`<div class="row"><div><b>${esc(r.name)}</b><div class="routine-ex">${r.ex.map(esc).join(' · ')}</div></div><button class="danger" onclick="deleteRoutine(${i})">Eliminar</button></div>`).join('')||'<div class="empty">No hay rutinas.</div>'}window.deleteRoutine=i=>{db.routines.splice(i,1);save()};
function renderExercises(){$('#exerciseList').innerHTML=db.exercises.map((e,i)=>`<div class="exercise-card"><b>${esc(e)}</b><button class="danger" style="float:right" onclick="deleteExercise(${i})">Eliminar</button></div>`).join('')}window.deleteExercise=i=>{db.exercises.splice(i,1);save()};
function modal(title,html,submit){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden');submit()};$('#closeModal').onclick=()=>$('#modal').classList.add('hidden');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.add('hidden')};
$('#newRoutine').onclick=()=>modal('Nueva rutina',`<div class="form"><input id="rname" class="input" placeholder="Nombre (ej. Upper A)"><input id="rex" class="input" placeholder="Ejercicios separados por coma"><button class="primary" id="ok">Guardar</button></div>`,()=>$('#ok').onclick=()=>{let n=$('#rname').value.trim();if(!n)return;db.routines.push({name:n,ex:$('#rex').value.split(',').map(x=>x.trim()).filter(Boolean)});$('#modal').classList.add('hidden');save()});
$('#newExercise').onclick=()=>modal('Nuevo ejercicio',`<div class="form"><input id="ename" class="input" placeholder="Nombre del ejercicio"><button class="primary" id="ok">Guardar</button></div>`,()=>$('#ok').onclick=()=>{let n=$('#ename').value.trim();if(n&&!db.exercises.includes(n))db.exercises.push(n);$('#modal').classList.add('hidden');save()});
function renderAll(){renderDashboard();renderHistory();renderRoutines();renderExercises()}renderAll();newWorkout();
